services:
  multi-asr-server:
    image: multi-asr-server
    ports:
      - "3010:3010"
    environment:
      - PORT=3010
    networks:
      - webnet

  edge-streamer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - multi-asr-server
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
