services:
  multi-asr-server:
    image: multi-asr-server
    ports:
      - "3010:3010/udp"
    environment:
      - PORT=3010
    networks:
      - webnet

  edge-streamer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - multi-asr-server
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - webnet
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true

networks:
  webnet:
    driver: bridge
